-- Schema as previously generated by Hibernate (ddl-auto: update).
CREATE TABLE tenant_faqs (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    answer    varchar(3000),
    question  varchar(1000),
    tenant_id bigint
);
