-- Schema as previously generated by Hibernate (ddl-auto: update). Constraint names are kept identical so that
-- databases created by Flyway and existing databases adopted via baseline-on-migrate end up the same.

CREATE TABLE tenant (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255)
);

CREATE TABLE faq (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    answer    varchar(3000),
    question  varchar(1000),
    tenant_id bigint
);

CREATE TABLE admin_users (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    timestamp(6) with time zone,
    password_hash varchar(255) NOT NULL,
    role          varchar(20) DEFAULT 'SUPER_ADMIN' NOT NULL
        CONSTRAINT admin_users_role_check CHECK (role IN ('SUPER_ADMIN', 'TENANT_ADMIN')),
    token_version integer DEFAULT 0 NOT NULL,
    username      varchar(255) NOT NULL CONSTRAINT uk3fgxk4ewgaxgtgvqwb1jjudj6 UNIQUE
);

CREATE TABLE admin_user_tenants (
    admin_user_id bigint NOT NULL CONSTRAINT fkb57sfjhbfhigvnhndxm98vd7c REFERENCES admin_users (id),
    tenant_id     bigint NOT NULL CONSTRAINT fkc8ce4qvfl6rv3yo6h9kicow6s REFERENCES tenant (id),
    PRIMARY KEY (admin_user_id, tenant_id)
);
